### ISSUE TITLE
2 issues, Uthgerd has a black face, and textures are broken for stockings

### ISSUE THREAD

**Issue by TheCampingOwl** [ForgottenGlory/Dungeons-Deviousness#62] opened 2021-01-13 13:43 UTC
I cannot attach a save file before the problem started, as the problem has been there since the start. If it's of help to you I can still give you the save file with the problem active.

**D&D Version**
No idea how to check, I downloaded this pack 2 days ago for the first time ever so I'd assume the latest one.

**Describe the bug**
I started the game in Whiterun as a property owner, went directly to the Bannered Mare, Uthgerd has a black face, while stocking textures are broken on both the player character and NPCs

**To Reproduce**
Steps to reproduce the behavior: Start game, configure MCM as according to the guide, go to Bannered Mare and look at Uthgerd and Leah. Alternatively, equip stockings. They appear to be broken too.

**Expected behavior**
Not have the stockings merge with my body, and Uthgerd being white or whatever her skin color is.

**Screenshots**
https://imgur.com/a/Ssj0swa

**Additional context**
Fresh install file, nothing else was done other than starting the game, and going directly to the Bannered Mare, the bodyslide files I use are the ones pre-built provided here: https://forgottenglory.github.io/readme/dnd/#prebuilt-bodyslides

The character isn't a prebuilt one, it's one i created myself, however, I have tried with a prebuilt character, Megan(Forgotten Glory) to be exact, and the same problem exists.

**Comment by celadoneiron** [comment] 2021-01-20 13:04
I think I may have tracked the cause down to an inconsistency between the install order of the NPC overhauls affecting Uthgerd - and Jenassa, who has the same issue - and the load order of the related .esps within D&D NPCs Merged. The merge places Whiterun2.esp from "Ladies of Whiterun NPC SSE - CBBE (SE) Curvy - Special Physics - v1.4.0" last, after PAN_LethalLadies.esp (Jenassa) and PAN_WarriorWomen.esp (Uthgerd). However, the install order in the left pane has the Pandorable mods below the Ladies of Whiterun mod.

When I moved the Ladies of Whiterun mod below Lethal Ladies and Warrior Women in the left pane, Uthgerd and Jenassa had normal face colours matching their bodies. I haven't tried making a replacement merge with the esp load orders rearranged to see if that would also work.

**Comment by ForgottenGlory** [comment] 2021-01-30 00:20
Fixed 1.4.0

**Closed by ForgottenGlory** 2021-01-30 00:20 UTC
Labels: bug
